module.exports = {
  TRULIOO_URL: 'http://distributed-api.instarem.com/trulioo_service/validate',
  REUTERS_TOKEN_URL: 'https://api.rkd.reuters.com/api/TokenManagement/TokenManagement.svc/REST/Anonymous/TokenManagement_1/CreateServiceToken_1',
  REUTERS_RATE_URL: 'http://api.rkd.reuters.com/api/Quotes/Quotes.svc/REST/Quotes_1/RetrieveItem_3',
  REUTERS_RATE_FIELDS: 'CF_LAST:CF_HIGH:CF_LOW:CF_BID:CF_ASK:CF_YIELD:CF_SOURCE:CF_SRC_PAGE:CF_LOTSIZE:CF_DATE:CF_TIME:CF_TICK:CF_NETCHNG:CF_EXCHNG:CF_VOLUME:CF_CLOSE:CF_OPEN:CF_NAME:CF_CURRENCY',
  MARGIN: 0.25,
  CURRENCY_PAIR: {
    EURHKD: 'EURHKD=X',
    EURMYR: 'EURMYR=X',
    EURINR: 'EURINR=X',
    EURTHB: 'EURTHB=X',
    EURSGD: 'EURSGD=X',
    EURGBP: 'EURGBP=X',
    EURPHP: 'EURPHP=R',
    EURLKR: 'EURLKR=R',
    EURUSD: 'EUR=X',
    EURCNY: 'EURCNY=X',
    USDGBP: 'USDGBP=R',
    USDEUR: 'USDEUR=R',
    USDSGD: 'SGD=X',
    USDTHB: 'THB=X',
    USDINR: 'INR=X',
    USDMYR: 'MYR=X',
    USDPHP: 'PHP=X',
    USDLKR: 'LKR=X',
    USDUSD: 'USD=X',
    USDMOP: 'MOP=X',
    USDTWD: 'TWD=X',
    USDHKD: 'HKD=X',
    USDCNY: 'CNY=X',
  },

};